In [7]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')
print(df)



   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [8]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
df.fillna(df.mean(), inplace=True)

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [9]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

print(model.predict([[6]]))


[12.]


In [10]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [15]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1,0,1]  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)

print(model.predict([[6, 8]]))



[1]


In [25]:
#6.import pandas as pd

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['Category']])  # Convert to 2D

print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [29]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0,1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

print("X_train:",X_train)
print("y_train:",y_train)





X_train: [[7, 8], [1, 2], [5, 6]]
y_train: [1, 0, 0]


In [32]:
#7.from sklearn.linear_model import LogisticRegression

from sklearn.preprocessing import LabelEncoder
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
model = LogisticRegression()
model.fit(X_train, y_train_encoded)

print(model.predict([[4, 6]]))


[1]


In [33]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer


# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

imputer = SimpleImputer(strategy="mean")
X_train_imputed = imputer.fit_transform(X_train)

# Train the model
model = LinearRegression()
model.fit(X_train_imputed, y_train)

# Make a prediction
prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)


Predicted Output: [20.]


In [36]:
#9.
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

model.fit(X_train, y_train_encoded)
print(model.predict([[2, 3]]))

[0.66666667]


In [39]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model.fit(X_train_scaled, y_train)

X_test_scaled = scaler.transform([[1, 150]])
print(model.predict(X_test_scaled))

[0]
